name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Copy build files to root
      run: |
        cp dist/index.html .
        cp -r dist/assets .

    - name: Commit and push
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add index.html assets/
        git diff --staged --quiet || git commit -m "Deploy: Update GitHub Pages files"
        git push origin main || true